#!/bin/sh
# Copyright 2006-2007 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

if [ "x${NO_POSTSYNC}" = "x1" ]; then
    exit 0
fi
if [ -d /etc/portage/postsync.d/ ]; then
    for f in /etc/portage/postsync.d/* ; do
        if [ -x ${f} ] ; then
            ${f} "$@"
        fi
    done
else
    :
fi
